### ISSUE TITLE
Single account deployment fails in preSolutionArtefactsStack

### ISSUE THREAD

**Issue by allquixotic** [aws-samples/aws-sso-extensions-for-enterprise#34]
When using the same AWS account and region for all accounts (target, orgmain, ssoservice and deployment), the CFT for preSolutionArtefactsStack fails creating `env-orgEventsNotificationsTopicArn`, because a resource with the same name already exists in `orgEventsProcessorStack`.

If the SSO extensions for enterprise cannot be used without at least some of the accounts or regions being distinct, this should be mentioned in the docs. Specifically, the docs should describe which of the four accounts (target, orgmain, ssoservice, and deployment) *must* be distinct for deployment to succeed. I am following the Workshop for deployment instructions.

Otherwise, if it should be possible to deploy to a single account and region, then this should be considered a bug.

**Comment by leelalagudu** [comment]
Hi @allquixotic , thank you for raising this issue. 

The solution should work for any pattern deployments i.e. single account + region , single account / multi region , multi account / single region, multi account / multi region. 

Based on the info provided, I think I had used the same logical construct ID for 2 different resources which is causing the issue you're seeing.

I will work on the fix and merge the change soon.

Thank you,
Leela

**Comment by leelalagudu** [comment]
Hi @allquixotic , [v3.0.1](https://github.com/aws-samples/aws-sso-extensions-for-enterprise/releases/tag/v3.0.1) should now fix this issue and you should be able to successfully deploy for any deployment pattern described above. 

Could you please give this a try and let us know what you think?

**Comment by allquixotic** [comment]
Confirmed v3.0.1 works in single-region + single-account setup. Thank you!
