### ISSUE TITLE
Migrating Fine-grained Per-account RBAC from AWS Directory Service

### ISSUE THREAD

**Issue by allquixotic** [aws-samples/aws-sso-extensions-for-enterprise#46]
_Originally "Problem 2" from #42_

This is a feature request and business justification is supplied.

### Assumptions:

**Note:** Not _all_ of these assumptions must be true for a potential solution to have value.

- The organization has many member accounts. The number is high enough that automation is desired.
- The organization has many users. The number is high enough that automation is desired.
- The organization currently uses AWS Directory Service to authenticate and authorize users.
  - Users are allowed to assume a role upon accessing the AWS Console based on the definitions in the **Delegate console access** section of AWS Directory Service (under Application Management).
  - The role the user assumes has an established Trust Relationship to assume role into various scoped roles within the desired member account.
  - Users log in using a directory portal on awsapps.com, which then prompts them for which delegated console access role they wish to assume.
 - For Least Privilege reasons, each user is only delegated roles for accounts they need. Example, if we have 50 accounts, a single user might be able to assume 1 to 5 roles depending on their individual need.
 - Most (but not all) of the IAM roles in the member accounts that get assumed, are _different_ from each other... there isn't a standard cookie-cutter "persona" or set of personas that apply to all accounts.
 - The organization wishes to **migrate** from the existing Directory Service based login to AWS SSO, while maintaining the current Least Privilege RBAC, consisting of thousands of data points associating users with the roles they are allowed to assume.
 - The users do **not** have AD Groups already assigned to them that correspond to the IAM roles they have in Directory Services' delegated console access.

### Problem:

 - In our **Delegate console access** list in Directory Services, there are _thousands_ of data points (user -> IAM role mappings). Manually recreating all these data points as AD Groups + Permission Sets + Accounts would take weeks of man-hours of work, and would be error-prone.
 - We will have to create all the appropriate permission sets and groups in AWS SSO and AD (or, if not in AD, at least in AWS SSO!)
 - Ongoing maintenance question: where do we store this data in a way that it's versioned and auditable? Even if we had 0 users currently, this would be an issue.

### Ad-Hoc Automation Solution:

Not yet implemented, but I am envisioning another script that reads all the roles, policies and access delegations from our current Directory Service (it will need cross account IAM access into each member account to read the policies underlying each role) and uses that as a data source to recreate an equivalent using Permission Sets and Groups in AWS SSO.

**Update:** I am concerned that this might not work. I can't find an API to access the **Delegate console access** list. See https://stackoverflow.com/questions/70903608/aws-directory-service-delegate-console-access-api-or-cli-command

### What Could SSO Extensions Do:

Something similar to the ad-hoc, but with self-maintenance using CodePipeline, and more configurable / robust than what I'll probably build ...

**Comment by allquixotic** [comment]
I still haven't found any way to programmatically access the role/user mappings in `Delegate console access`  other than web-based screen scraping (which sadly may end up being the route we take, because our timeline for SSO rollout is very aggressive). It seems like a glaring oversight in the AWS Directory Service API that no API exists to at least read this list. 

Since there is no API to do this, and screen scraping would not be a suitable solution for a robust tool like SSO Extensions, I'm guessing this will have to go into `blocked` state until, someday, AWS introduces an API for `Delegate console access`.

**Comment by leelalagudu** [comment]
@allquixotic  as discussed 2 months ago (yep, sorry about the delayed update) - we are providing automated provisioning for identity sources that do not have SCIM support through https://github.com/aws-samples/aws-sso-extensions-for-enterprise/issues/42 . In favour of that issue, I'm closing the current one, as the team cannot do anything from a directory service API limiation point of view. Please do let us know if you would like us to tackle anything else regarding the current issue, and we will raise a new issue for that. 

Thank you.
