### ISSUE TITLE
CloudWatch Logs Insights query name typos

### ISSUE THREAD

**Issue by ehinckley-code** [aws-samples/aws-sso-extensions-for-enterprise#59]
The following CloudWatch Logs Insights query names have typos, **Relateed** should be changed to **Related**:

- env-accountAssignmentAPIFlows-get**Relateed**RequestDetails
- env-orgEventsTriggerFlows-get**Relateed**RequestDetails
- env-permissionSetAPIFlows-get**Relateed**RequestDetails
- env-permissionSetSyncTriggerFlows-get**Relateed**RequestDetails
- env-ssoGroupTriggerFlows-get**Relateed**RequestDetails

**Comment by leelalagudu** [comment]
@vpegg , please include this fix as part of the nightlyRun PR
