### ISSUE TITLE
Typo in Json Schema

### ISSUE THREAD

**Issue by debojitmegaco** [aws-samples/aws-sso-extensions-for-enterprise#97]
https://github.com/aws-samples/aws-sso-extensions-for-enterprise/blob/6911cbed332710ae164807e06686c11620f372d8/lib/payload-schema-definitions/Link-S3.json#L31

Currently the Json Schema for ```"pattern": "account\\d{12}%[\\w+=,.@-]{1,32}%[_\\-\\p{L}\\p{M}\\p{S}\\p{N}+@.]{1,128}%USER%ssofile"``` has a typo and missing delimeter ```%```

**Comment by debojitmegaco** [comment]
@leelalagudu, Have submitted a Pull request for the Json Schema Update
https://github.com/aws-samples/aws-sso-extensions-for-enterprise/pull/98

**Comment by leelalagudu** [comment]
Hi @debojitmegaco , thank you for the PR. I had reviewed and approved the changes, however I don't have merge permissions. @jmejco  / @tamara-h  would be able to do this when they have some free time

**Comment by jmejco** [comment]
Closed by https://github.com/aws-samples/aws-sso-extensions-for-enterprise/pull/98
